--- # directory creation
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: creting a directory
      file:
        path: /home/ansible/awsdirectory
        state: directory

