--- # deleting a directory
- hosts: webservers
  user: ansible
  become: true
  connection: ssh
  tasks:
    - name: deleting a directory
      file:
        path: /home/ansible/awsdirectory
        state: absent

