--- # deleting a file
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: deleting a file
      file:
        path: /home/ansible/projectworkfile1
        state: absent


