--- # my handlers playbook
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: installing httpd into webservers
      action: yum name=httpd state=installed 
       
      notify: start httpd service
  handlers:

    - name: start httpd service
      action: service name=httpd state=started

