--- # my loops playbook
- hosts: all
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: installing multiple packages
      yum: name='{{item}}' state=installed
      with_items: 
            - httpd
            - git
            - tree
            - mysql
            - docker
            - java

